### ISSUE TITLE
스터디 진행방식 고민 & 정리

### ISSUE THREAD

**Issue by ABizCho** [SSAFY-front-scholars/front-scholars#1]
# 스터디 진행방식 고민 & 정리

### 1. Vanilla JS 구현

- Carousel
- Modal
- infinite Scroll
- drag-and-drop (dnd)

![dnd](https://github.com/SSAFY-front-scholars/front-scholars/assets/65459616/6cd3b517-05bd-4ede-8cb1-d0320623b1a9)

- Simple SPA 프로젝트
 1. vanillaJS로 SPA의 State, Component, 코어 Hooks
 2. SPA 라우팅 구현
 3. 전역상태관리 라이브러리 구현 or 클론

<br/>

### 2. React 구현 
(후보군 : 미정)

- [react-realworld](https://github.com/angelguzmaning/ts-redux-react-realworld-example-app?tab=readme-ov-file)
- 기업 프로젝트 클론 도전?
- 과제전형 도전?

<br/>

### 3. 독서 스터디, 기술 스터디
(후보군 : 미정)

- 상태 관리 방법론 및 라이브러리 비교분석
...

---

### 7. 이력서, 포트폴리오, 자소서, 면접 대비

---

@brobac 같이 정리해나갑시다

**Comment by ABizCho** [comment]
스토리북 어케 활용하나 실습해보고 싶긴한데 관심있음?
@brobac

**Comment by brobac** [comment]
### 기본조건

- vinilla js와 CSS를 사용한다.
- 몇 번째 슬라이드인지 알려주는 인디케이터
- 앞, 뒤 슬라이드로 넘어가는 버튼
- 무한 슬라이드
    - 마지막슬라이드 다음 슬라이드는 처음슬라이드
    - 처음슬라이드 이전 슬라이드는 마지막슬라이드
    - transform, animation 등을 사용하여 움직임을 구현할 것

### 추가조건

- N초 후 자동 슬라이드전환 + 몇초뒤에 넘어가는지 인디케이터 보여주기
    - [농협 라이블리 참고](https://nhlyvly.com/)
- 현재 슬라이드 뿐만 아니라 양 옆 슬라이드도 보여주기 (농협 라이블리 참고)
- 슬라이드 크기가 동적으로 변해도 동작하도록 구현
- 재생, 정지 버튼 추가
- 특정인덱스로 이동(인디케이터 클릭 등)
